{{- if .Values.librechat.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "librechat.fullname" . }}-hpa
  labels:
    {{ include "librechat.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "librechat.fullname" . }}
  minReplicas: {{ .Values.librechat.hpa.minReplicas }}
  maxReplicas: {{ .Values.librechat.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.librechat.hpa.targetCPUUtilization }}
{{- end }}
