{{- if .Values.dofile.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "librechat.fullname" . }}-dofile
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
spec:
  storageClassName: nfs-rwx-storage
  accessModes:
    - {{ .Values.dofile.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dofile.storageSize }}
{{- end }}
